// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title:{
//    // absolute:"gaga",
// default:"default",
// template:"%s|default ياغاده",
//   },
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }:{
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css'
import Header from './componenets/header/Header';
import Footer from './componenets/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cloud Hosting',
  description: 'Cloud hosting project',
}

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ToastContainer theme='colored' position='top-center' />
        <main>
         {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
